### ISSUE TITLE
mvn编译错误，jdk版本17

### ISSUE THREAD

**Issue by dingafter** [whgojp/JavaSecLab#4]
![image](https://github.com/user-attachments/assets/d4c991e8-0e58-4283-9e3b-bbf310fd7c68)
应该是jdk版本太高的问题，当前开发使用java版本是多少呀？

**Comment by whgojp** [comment]
<img width="768" alt="image" src="https://github.com/user-attachments/assets/75c31640-f47f-492a-9a61-674a851e95f3">
