### ISSUE TITLE
这不是抄的Hello-Java-Sec？

### ISSUE THREAD

**Issue by ctfer888** [whgojp/JavaSecLab#5]
https://github.com/j3ers3/Hello-Java-Sec

**Comment by whgojp** [comment]
看你怎么理解抄袭了，技术架构不一样，我理解开源本身就是鼓励代码共享和协作
确实参考了Hello-Java-Sec项目，DashBoard中也有标注了参考来源
要是说代码重复了，那我无话可说，毕竟就那么多种漏洞类型
不做过多解释……
<img width="584" alt="image" src="https://github.com/user-attachments/assets/a74b3495-d762-4382-8311-ef603d7f4d10">
