### ISSUE TITLE
登录后重定向到/error

### ISSUE THREAD

**Issue by 1282618226** [whgojp/JavaSecLab#6]
为什么登录之后会重定向到error
![image](https://github.com/user-attachments/assets/9b00ad2a-a84a-4a44-b626-f035092dfb08)

**Comment by whgojp** [comment]
麻烦师傅给多一些细节哈，看一下容器日志

**Comment by 1282618226** [comment]
抓登录的请求，响应就是302，重定向到/error界面。
![image](https://github.com/user-attachments/assets/1068607e-630e-41b2-8b16-b13d3dbedc5e)
看idea控制台输出，这里有个spring security检测到http://，这里的双斜杠就会报错，不知道有没有这个的影响。
![image](https://github.com/user-attachments/assets/ef3de167-d551-43a4-acd0-526d2cf45d07)
![image](https://github.com/user-attachments/assets/ba85cf64-88f5-44a7-bba7-c477bf784113)
其他的倒是没什么报错了。我看演示站点也会的。
![image](https://github.com/user-attachments/assets/458c694c-f404-4312-9ea9-58573afa6fba)

**Comment by 1282618226** [comment]
没抓包也会呀，http://whgojp.top/这个也会跳转到error，你那边登不会吗

**Comment by 1282618226** [comment]
神奇，换一台电脑又不会了

**Comment by whgojp** [comment]
应该是浏览器问题🤔
